# Generated by Django 3.1 on 2021-02-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
