# Generated by Django 3.1.2 on 2021-02-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20210224_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hit',
            new_name='hits',
        ),
        migrations.AddField(
            model_name='post',
            name='top_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
